### ISSUE TITLE
How do you compile this thing

### ISSUE THREAD

**Issue by TheStaticTurtle** [earthquake/chw00t#4]
All is in the title

**Comment by earthquake** [comment]
Added a new paragraph to the readme. I did not think it is necessary, but it is most certainly useful.

**Comment by TurtleForGaming** [comment]
Got:
`chw00t.c: In function 'ptracepid':
chw00t.c:845:29: error: storage size of 'regs' isn't known
     struct user_regs_struct regs;
`

**Comment by earthquake** [comment]
What kind of OS, architecture and compiler do you use?
