### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by TheStaticTurtle** [earthquake/chw00t#5]
I'm geting an compilation erro while compileing with the command in the README

```
root@kali:~/chw00t# gcc chw00t.c -o chw00t -static
chw00t.c: In function 'ptracepid':
chw00t.c:845:29: error: storage size of 'regs' isn't known
     struct user_regs_struct regs;

```

**Comment by earthquake** [comment]
Could you send the following outputs to me please:
\# uname -a
\# gcc -v

**Comment by earthquake** [comment]
additionally, do you have the headers installed for your kernel?

**Comment by TheStaticTurtle** [comment]
uname -a
> Linux kali 3.4.67-cyanogenmod-g399b32b #4 SMP PREEMPT Sun Dec 13 22:58:40 UTC 2015 armv7l GNU/Linux

gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.9/lto-wrapper
> Target: arm-linux-gnueabihf
> Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
> Thread model: posix
> gcc version 4.9.2 (Debian 4.9.2-10)

I don't really know if I have the headers installed but I can build an another program

**Comment by earthquake** [comment]
Oh I see. You are trying to compile the stuff for ARMv7, but it has no support for ARM. The ptrace functionality (which is failing) only supports x86 and x64 architectures but no ARM. Unfortunately I do not have access to an ARM device at the moment, so I will not be able to fix this, but it should not be hard. Feel free to fix it and send me a pull request if you would like.
Alternatively, just comment out the ptrace related codes, the others should work without any issues.
